# Generated by Django 4.2.5 on 2023-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
